<?php
declare(strict_types=1);
namespace OtraUser\bundles\OtraUser\frontend\views\index;
use const otra\cache\php\BASE_PATH;
use function otra\cache\php\block;

/**
 * @var string $viewPath
 */
require BASE_PATH . 'bundles/OtraUser/views/layout.phtml';

const USERS_MANAGEMENT_TITLE = 'Backoffice - Users management';
block('title', USERS_MANAGEMENT_TITLE);
block('page', 'users-page');
block('meta-description', USERS_MANAGEMENT_TITLE);
block('application-name', USERS_MANAGEMENT_TITLE);
block('og-site-name', USERS_MANAGEMENT_TITLE);
require $viewPath . 'partials/usersBody.phtml';
