
<link rel="stylesheet" nonce="my-nonce" href="/bundles/OtraUser/backoffice/resources/css/pages/users/users.css" media="screen"/><button type="button" class="ripple logout -logout">Log out</button><table class="table suffix"><thead class="table-header"><tr><th>Id</th><th>Pseudo</th><th>First name</th><th>Last name</th><th>Mail</th><th>Token</th><th>Role</th></tr></thead><tbody><tr><td data-label="id">
        1        </td><td data-label="pseudo">
        Johnny        </td><td data-label="first_name">
        John        </td><td data-label="last_name">
        Smith        </td><td data-label="mail">
        contact@website.com        </td><td data-label="token">
        null        </td><td data-label="mask"><div class="select select-container"><button type="button" role="menu" class="select select-value"><span class="select select-value--label">admin</span><span>&#x25bc;&#xfe0e;</span></button><div class="select select-list"><input type="radio" role="menuitem" id="chk-1-admin-option"
                         name="1-select-radio"
                         class="select select-item--activator" value="admin" checked/><label for="chk-1-admin-option" class="select select-item--label">admin</label><input type="radio" role="menuitem" id="chk-1-moderator-option"
                         name="1-select-radio"
                         class="select select-item--activator" value="moderator"/><label for="chk-1-moderator-option" class="select select-item--label">moderator</label></div></div></td></tr><tr><td data-label="id">
        2        </td><td data-label="pseudo">
        MrPaul        </td><td data-label="first_name">
        Paul        </td><td data-label="last_name">
        Brown        </td><td data-label="mail">
        contact@website2.com        </td><td data-label="token">
        null        </td><td data-label="mask"><div class="select select-container"><button type="button" role="menu" class="select select-value"><span class="select select-value--label">moderator</span><span>&#x25bc;&#xfe0e;</span></button><div class="select select-list"><input type="radio" role="menuitem" id="chk-2-admin-option"
                         name="2-select-radio"
                         class="select select-item--activator" value="admin" checked/><label for="chk-2-admin-option" class="select select-item--label">admin</label><input type="radio" role="menuitem" id="chk-2-moderator-option"
                         name="2-select-radio"
                         class="select select-item--activator" value="moderator"/><label for="chk-2-moderator-option" class="select select-item--label">moderator</label></div></div></td></tr></tbody></table><script nonce="my-nonce" src="/cache/js/my-nonce.gz" async defer></script><?php
