<?php
declare(strict_types=1);
/**
 * @var array $users
 * @var array $roles
 */
?>
<table class="table suffix">
  <thead class="table-header">
    <tr>
      <?php
      foreach(array_keys($users[0]) as &$userKey)
      {
        if ($userKey === 'mask')
          $userKey = 'Role';

      ?><th><?= ucfirst(str_replace('_', ' ', $userKey)) ?></th><?php
      }
      unset($userKey);
      ?>
    </tr>
  </thead>

  <tbody>
    <?php foreach ($users as $userKey => $user)
    {
    ?><tr><?php
      foreach($user as $userInformationKey => $userInformation)
      {
        $userValue = $userInformation ?? 'null';
      ?><td data-label="<?= $userInformationKey ?>"><?php
        if ($userInformationKey === 'pseudo')
        {
          echo $userValue;?>
          <br/>
          <div class="table--row--links">
            <button class="table--link">Modify</button>&nbsp;|&nbsp;<!--
          --><button data-user-id="121" class="table--link -trash" data-route="userTrash">Delete</button
          </div><?php
        }
        elseif ($userInformationKey === 'mail')
        {
          ?><a href="@mailto:<?= $userValue?>"><?= $userValue ?></a><?php
        }
        elseif ($userInformationKey !== 'mask')
          echo $userValue;
        else
          echo $roles[$userValue];
        ?>
        </td><?php
      }
    ?></tr><?php
    }?>
  </tbody>
</table>
