<?php
declare(strict_types=1);
namespace OtraUser\bundles\OtraUser\frontend\views\index;
use const otra\cache\php\BASE_PATH;
use function otra\cache\php\{block, endblock};

require BASE_PATH . 'bundles/OtraUser/views/layout.phtml';
const LOGIN_TITLE = 'Login';
block('title', LOGIN_TITLE);
block('meta-description', LOGIN_TITLE);
block('application-name', LOGIN_TITLE);
block('og-site-name', LOGIN_TITLE);
block('page', 'login-page');
block('body');


if (!isset($_SESSION['sid']))
{
?>
<form class="login-box flex-container suffix-2" method="POST" enctype="application/x-www-form-urlencoded">
  <h1 class="otra-login--title">Login</h1>
  <div class="field-group">
    <label for="otra-login" class="label ec-icon ec-bust-in-silhouette required login-box--label">Username or email</label>
    <input id="otra-login" class="field" name="otra-email" autocomplete="username" autofocus required />
  </div>

  <div class="field-group">
    <label for="otra-password" class="label ec-icon ec-key required login-box--label">Password</label>
    <input id="otra-password" type="password" class="field" name="otra-password" autocomplete="current-password" required />
  </div>

  <div class="field-group field-group--remember">
    <input type="checkbox" id="otra-remember" name="otra-remember" class="otra-remember--checkbox"/>
    <label for="otra-remember" class="label login-box--label">Remember me</label>
  </div>

  <div class="field-group error-message error-message--hidden">
    Wrong credentials.
  </div>

  <input type="submit" class="ripple login-box--submit" value="Log in"/>
</form>
<?php endblock();
} else
{
  ?>You are already logged!<br><?php
}
